//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxBusters.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FallOut_TBL
    {
        public long Id { get; set; }
        public string FileName { get; set; }
        public string Lot { get; set; }
        public string Section { get; set; }
        public string Block { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
