//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyTaxBusters.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAssessedValue_TBL
    {
        public long Id { get; set; }
        public long PropertyId { get; set; }
        public string Year { get; set; }
        public Nullable<long> AssessedValue { get; set; }
        public string TaxRollStatus { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> ModifyBy { get; set; }
    
        public virtual Property_TBL Property_TBL { get; set; }
    }
}
